[package]
name = "feignx-reqwest"
description = "Reqwest transport implementation for feignx"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }

[dependencies]
feignx-core = { workspace = true }
reqwest = { workspace = true }
async-trait = { workspace = true }
http = { workspace = true }
bytes = { workspace = true }
reqwest-middleware = { workspace = true, optional = true }
reqwest-retry = { workspace = true, optional = true }
reqwest-tracing = { workspace = true, optional = true }
backon = { workspace = true, optional = true }

[features]
default = []
middleware = ["dep:reqwest-middleware"]
retry = ["middleware", "dep:reqwest-retry", "dep:backon"]
tracing = ["middleware", "dep:reqwest-tracing"]