[package]
name = "rfeign-core"
description = "Core traits and types for rfeign declarative HTTP client"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
readme = "README.md"
categories = { workspace = true }
keywords = { workspace = true }

[dependencies]
http = { workspace = true }
bytes = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
base64 = { workspace = true }
erased-serde = { workspace = true }
serde_urlencoded = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
recloser = { workspace = true, optional = true }

[features]
default = []
circuit-breaker = ["dep:recloser"]