[package]
name = "feignx"
description = "A declarative HTTP client for Rust, inspired by OpenFeign"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }

[dependencies]
feignx-core = { workspace = true }
feignx-macros = { workspace = true }
feignx-reqwest = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
bytes = { workspace = true }
http = { workspace = true }
async-trait = { workspace = true }
serde_urlencoded = { workspace = true }
nacos-sdk = { workspace = true, optional = true }

[features]
default = ["reqwest", "json"]
reqwest = ["dep:feignx-reqwest"]
json = ["dep:serde_json"]
retry = ["reqwest", "feignx-reqwest/retry"]
tracing = ["reqwest", "feignx-reqwest/tracing"]
middleware = ["reqwest", "feignx-reqwest/middleware"]
circuit-breaker = ["feignx-core/circuit-breaker"]
middleware-full = ["retry", "tracing", "circuit-breaker"]
nacos = ["dep:nacos-sdk"]