[package]
name = "rfeign"
description = "A declarative HTTP client for Rust, inspired by OpenFeign"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
readme = "../README.md"
categories = { workspace = true }
keywords = { workspace = true }

[dependencies]
rfeign-core = { workspace = true }
rfeign-macros = { workspace = true }
rfeign-reqwest = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
bytes = { workspace = true }
http = { workspace = true }
async-trait = { workspace = true }
serde_urlencoded = { workspace = true }
nacos-sdk = { workspace = true, optional = true }
rs-consul = { workspace = true, optional = true }

[features]
default = ["reqwest", "json"]
reqwest = ["dep:rfeign-reqwest"]
json = ["dep:serde_json"]
retry = ["reqwest", "rfeign-reqwest/retry"]
tracing = ["reqwest", "rfeign-reqwest/tracing"]
middleware = ["reqwest", "rfeign-reqwest/middleware"]
circuit-breaker = ["rfeign-core/circuit-breaker"]
middleware-full = ["retry", "tracing", "circuit-breaker"]
nacos = ["dep:nacos-sdk"]
consul = ["dep:rs-consul"]

[dev-dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }