[package]
name = "example-with-summer"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
rfeign = { path = "../../rfeign", features = ["summer"] }
rfeign-core = { path = "../../rfeign-core" }
summer-rfeign = { path = "../../summer-rfeign", features = ["nacos"] }
summer = { workspace = true }
summer-web = { workspace = true }
summer-nacos = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
